[package]
name = "audio_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bwavfile = "1.1.0"
byteorder = "1.4.3"
hound = "3.5.0"
iter_num_tools = "0.6.2"
itertools = "0.10.5"
itertools-num = "0.1.3"
nalgebra = "0.31.2"
ndarray = "0.15.6"
num-traits = "0.2.15"
secded = {version="1.1.0",features=["dyn"]}
